#!/usr/bin/env bash
# sync-codex-skills.sh - Sync .agent/ content to OpenAI Codex
#
# Creates:
# - .codex/skills/<name>/SKILL.md symlinks for skills
# - .codex/AGENTS.override.md containing concatenated agent policies
#
# Usage: ./scripts/boilerplate/sync-codex-skills.sh
# Integrated into: make sync
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

SRC_AGENT="${PROJECT_ROOT}/.agent"
DST_CODEX="${PROJECT_ROOT}/.codex"

echo "[codex] root=${PROJECT_ROOT}"

# Ensure base destination exists
mkdir -p "${DST_CODEX}"

# 1) Skills -> .codex/skills/<name>/SKILL.md (symlinks, matching Claude structure)
if [[ -d "${SRC_AGENT}/skills" ]]; then
  DST_SKILLS="${DST_CODEX}/skills"
  echo "[codex] Skills: ${SRC_AGENT}/skills -> ${DST_SKILLS}"

  # Clean and recreate skills directory (preserve .gitkeep if exists)
  if [[ -f "${DST_SKILLS}/.gitkeep" ]]; then
    rm -rf "${DST_SKILLS}/"*/ 2>/dev/null || true
    rm -f "${DST_SKILLS}/"*.md 2>/dev/null || true
  else
    rm -rf "${DST_SKILLS}" 2>/dev/null || true
    mkdir -p "${DST_SKILLS}"
  fi

  skill_count=0
  for skill_file in "${SRC_AGENT}/skills/"*.md; do
    if [[ -f "$skill_file" ]]; then
      skill_basename="$(basename "$skill_file")"
      skill_name="${skill_basename%.md}"

      # Create skill subdirectory
      skill_dir="${DST_SKILLS}/${skill_name}"
      mkdir -p "${skill_dir}"

      # Relative path from .codex/skills/<name>/ to .agent/skills/<name>.md
      ln -sf "../../../.agent/skills/${skill_basename}" "${skill_dir}/SKILL.md"
      echo "[codex]   skills/${skill_name}/SKILL.md -> ../../../.agent/skills/${skill_basename}"

      skill_count=$((skill_count + 1))
    fi
  done

  echo "[codex] Skills: OK (${skill_count} skills synced)"
else
  echo "[codex] Skills: no ${SRC_AGENT}/skills (skip)"
fi

# 2) Generate AGENTS.override.md from subagents (concatenated content)
# Codex uses AGENTS.override.md for project-level guidance
if [[ -d "${SRC_AGENT}/subagents" ]]; then
  override_file="${DST_CODEX}/AGENTS.override.md"
  echo "[codex] Generating: ${override_file}"

  # Write header
  cat > "${override_file}" << 'HEADER'
# Agent Policies for Codex

> **Auto-generated by `make sync`** — Do not edit directly.
> Source: `.agent/subagents/`

This file contains concatenated agent policies from the project's agent definitions.
Codex should apply these policies when working on this project.

HEADER

  agent_count=0
  for agent_file in "${SRC_AGENT}/subagents/"*.md; do
    if [[ -f "$agent_file" ]]; then
      agent_basename="$(basename "$agent_file")"
      agent_name="${agent_basename%.md}"

      # Add separator and agent name header
      echo "" >> "${override_file}"
      echo "---" >> "${override_file}"
      echo "" >> "${override_file}"
      echo "## ${agent_name^} Agent" >> "${override_file}"
      echo "" >> "${override_file}"

      # Extract content after frontmatter
      # Skip lines until we find the closing --- of frontmatter, then include the rest
      in_frontmatter=true
      frontmatter_count=0
      while IFS= read -r line || [[ -n "$line" ]]; do
        if [[ "$line" == "---" ]]; then
          frontmatter_count=$((frontmatter_count + 1))
          if [[ $frontmatter_count -ge 2 ]]; then
            in_frontmatter=false
            continue
          fi
          continue
        fi
        if [[ "$in_frontmatter" == "false" ]]; then
          echo "$line" >> "${override_file}"
        fi
      done < "$agent_file"

      agent_count=$((agent_count + 1))
    fi
  done

  echo "[codex] AGENTS.override.md: OK (${agent_count} agents concatenated)"
else
  echo "[codex] Agents: no ${SRC_AGENT}/subagents (skip AGENTS.override.md)"
fi

# Note: Commands are NOT synced - Codex doesn't support slash commands

echo "[codex] done"
